## code to prepare `empty` dataset goes here
empty <- list()

empty[["comment"]] <- tibble::tibble(
  all_awardings = I(list(list())),
  archived = NA,
  associated_award = NA_character_,
  author = NA_character_,
  author_flair_background_color = NA_character_,
  author_flair_css_class = NA_character_,
  author_flair_richtext = I(list(list())),
  author_flair_template_id = NA_character_,
  author_flair_text = NA_character_,
  author_flair_text_color = NA_character_,
  author_flair_type = NA_character_,
  author_fullname = NA_character_,
  author_patreon_flair = NA,
  author_premium = NA,
  body = NA_character_,
  body_sha1 = NA_character_,
  can_gild = NA,
  collapsed = NA,
  collapsed_because_crowd_control = NA_character_,
  collapsed_reason = NA_character_,
  collapsed_reason_code = NA_character_,
  comment_type = NA_character_,
  controversiality = NA_integer_,
  created_utc = NA_integer_,
  distinguished = NA_character_,
  gilded = NA_integer_,
  gildings = I(list(list())),
  id = NA_character_,
  is_submitter = NA,
  link_id = NA_character_,
  locked = NA,
  no_follow = NA ,
  parent_id = NA_character_,
  permalink = NA_character_,
  retrieved_utc = NA_integer_,
  score = NA_integer_,
  score_hidden = NA,
  send_replies = NA,
  stickied = NA,
  subreddit = NA_character_,
  subreddit_id = NA_character_,
  subreddit_name_prefixed = NA_character_,
  subreddit_type = NA_character_,
  top_awarded_type = NA_character_,
  total_awards_received = NA_integer_,
  treatment_tags = I(list(list())),
  unrepliable_reason = NA_character_
)
usethis::use_data(empty, overwrite = TRUE,internal = TRUE)
